// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSUx1qWO2-GVQ-LLR0WgXRGzKcCx76Nk',
    appId: '1:477688847048:web:d8224d146e8b0e318863fd',
    messagingSenderId: '477688847048',
    projectId: 'fire-chat-9dbeb',
    authDomain: 'fire-chat-9dbeb.firebaseapp.com',
    storageBucket: 'fire-chat-9dbeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1i-oZHzc1YciYAMbAh4HnqwjGucwIBCU',
    appId: '1:477688847048:android:0238fb74040b9def8863fd',
    messagingSenderId: '477688847048',
    projectId: 'fire-chat-9dbeb',
    storageBucket: 'fire-chat-9dbeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyFZ_QsYzxsB6X45voyazPaGOolS-jhk',
    appId: '1:477688847048:ios:565edb66530848908863fd',
    messagingSenderId: '477688847048',
    projectId: 'fire-chat-9dbeb',
    storageBucket: 'fire-chat-9dbeb.appspot.com',
    iosBundleId: 'com.example.fireChat',
  );
}
